[tool.poetry]
name = "test"
version = "0.0.0"
description = "Test array exchange"
authors = ["Alessandro Candido <candido.ale@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10,<3.11"
numpy = "^1.23.3"
scalene = "^1.5.13"


[tool.poetry.group.cuda.dependencies]
cupy-cuda11x = "^11.1.0"
tensorflow = "^2.10.0"
numba = "^0.56.2"


[tool.poetry.group.rocm.dependencies]
cupy-rocm-5-0 = "^11.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
